# Generated by Django 6.0.7 on 2026-07-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва фільму')),
                ('author', models.CharField(max_length=30, verbose_name='Режисер')),
                ('description', models.TextField(verbose_name='Опис фільму')),
                ('year', models.IntegerField(verbose_name='Рік випуску')),
                ('genre', models.CharField(max_length=30, verbose_name='Жанр')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
            },
        ),
    ]
